### PR TITLE
Fix a well known ld-preload issue

### PR DESCRIPTION
**Pull request by kaiwan**
Need to comment out the pathname in rootfs /etc/ld.so.preload as when uncommented the kernel panics on startup. (This issue isn't dead- I faced it on Ubuntu 16.10 yesterday :-)).
See [this SO](http://stackoverflow.com/questions/38837606/emulate-raspberry-pi-raspbian-with-qemu) Q&A as a reference.

### CODE REVIEW

**Comment by nachoparker** [comment]
Thank you

It is interesting because I do not need that for QEMU to boot properly.

What version of qemu-arm are you using? 

Also, what is the error ? maybe this? https://i.stack.imgur.com/B6nMO.png

In that case, it might be an issue that qemu-arm versions prior to 2.8.0 (the one that I am using). It seems that Ubuntu's version is not as up-to-date as the one in Arch.

I had a commenter on the blog with the same problem ( https://ownyourbits.com/2017/02/06/raspbian-on-qemu-with-network-access/#comment-152 ), but it seems that he fixed it in a different way.

**Comment by kaiwan** [comment]
>What version of qemu-arm are you using?

2.6.1 
>Also, what is the error ? maybe this? https://i.stack.imgur.com/B6nMO.png

Yes, exactly the same.

>In that case, it might be an issue that qemu-arm versions prior to 2.8.0 (the one that I am using). It >seems that Ubuntu's version is not as up-to-date as the one in Arch.

Ok.. My concern though is that this is a useful script, and among Linux users, Ubuntu is a very widely used distro; hence, having the script work correctly for Ubuntu is important and avoids a lot of frustration (including rebuilding qemu) for those users.

**Comment by nachoparker** [comment]
I aggree. The problem is that I do not like commenting that line, because I use `qemu-pi.sh` to work with images that then I can run on a real Raspberry Pi.

I developed this in order to build NextCloudPi 

https://ownyourbits.com/2017/02/13/nextcloud-ready-raspberry-pi-image/

On the other hand you are right, it saves time and frustration for many Ubuntu users... maybe we should create a branch for older `qemu-arm` versions and clarify that in the `README.md`

What do you think about that?

**Comment by kaiwan** [comment]
>On the other hand you are right, it saves time and frustration for many Ubuntu users... maybe we should create a branch for older qemu-arm versions and clarify that in the README.md

Agreed, should do that..

**Comment by nachoparker** [comment]
I ended up detecting the `qemu-arm` version, and commenting that line only in case it is needed without overwriting the whole file.

Please, test if it works for you.

Thank you

**Comment by kaiwan** [comment]
Yep, it works :-) . Thanks.

**Pull request merged**
